name: code_snippets
description: Code snippets from the open source community.
version: 0.0.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  crypto: ^3.0.1
  http: ^0.13.4
  logging: ^1.0.2
  mime: ^1.0.1
  path: ^1.8.1