name: Rust
on:
  push:
    paths:
      - "**.rs"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the directory
        uses: actions/checkout@v2
      - name: Update Rust
        run: rustup update
      - name: Install required components
        run: rustup component add clippy
      - name: Run the code
        run: |
          ALL_FILES_IN_DIRECTORY=$(find Rust/ -type f -name "*.rs")
          for CURRENT_FILE_IN_DIRECTORY in ${ALL_FILES_IN_DIRECTORY}; do
            ALL_FILES_LIST[${ADD_CONTENT}]=${CURRENT_FILE_IN_DIRECTORY}
            ADD_CONTENT=$(("${ADD_CONTENT}" + 1))
          done
          cd Rust/
          for FILE_LIST in "${ALL_FILES_LIST[@]}"; do
            echo ${FILE_LIST}
            mv ../${FILE_LIST} src/main.rs
            cargo run --quiet --all-features
            cargo clippy
            cargo clean
            mv src/main.rs ../${FILE_LIST}
          done
